---
- name: Playbook for Installing 1 packege
  hosts: "{{host}}"
  become: yes
  become_method: sudo
  tasks:
    - name: Install packege
      package:
      name: " {{ packege }}"
      state: present
