---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Download wordpress
      get_url:
        url: "https://wordpress.org/wordpress-5.2.3.zip"
        dest: /tmp/
    - name: Install unzip
      packege:
        name: unzip
        state: present
    - name: unzip
      unarchive:
        src: /tmp/wordpress-5.2.3.zip
        dest: /tmp
        remote_src: yes
      ignor_errors: true  