---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Download wordpress
      get_url:
      url: "https://wordpress.org/latest.zip"
      dest: /tmp/
    - name: Unzip
      unarchive:
        src: /tmp/wordpress-5.2.3.zip
        dest: /tmp
      ignor_errors: true  