---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: present
    - name: Start apache 
      systemd:
        name: httpd
        state: restarted   
    - name: Install firewalld
      yum:
        name: firewalld
        state: latest
    - name: Install telnet
      yum:
        name: telnet
        state: latest     

