---
- name: Playbook for task
  hosts: all
  becoms: yes
  becom_method: sudo
  tasks:
    - name: Install apache 
      yum:
        name: httpd
        state: present
    - name: Start apache
      systemd: 
        name: httpd
        state: restarted 