---
- name: Playbook for Provisioning
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
        - name: create a VPC with dedicated tenancy and a couple of tags
  ec2_vpc_net:
    name: Module_dev2
    cidr_block: 10.10.0.0/16
    region: us-east-2
    tags:
      module: ec2_vpc_net
      this: works
    tenancy: dedicated
         - name: Create Private subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: vpc-9807e9f3
    cidr: 10.0.1.16/28
    resource_tags:
      Name: Database Subnet
  register: database_subnet 