
- name: EC2 creates VPC on ohio region 
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
    - name: create VPC with tags
      ec2_vpc_net:
        name: Miki_VPC
        cidr_block: 10.0.0.0/16
        region: us-east-2
        tags:
          name: miki_VPC
          tenancy: default     
    - name: create subnet a
      ec2_vpc_subnet:
        state: present
        region: "{{vpc_region}}"
        vpc_id: "{{vpc.vpc.id}}"
        cidr: "{{subnet_cidr_b}}"
        az: "{{az_b}}"   
    - name: create subnet b
      ec2_vpc_subnet:
        state: present
        region: "{{vpc_region}}"
        vpc_id: "{{vpc.vpc.id}}"
        cidr: "{{subnet_cidr_b}}"
        az: "{{az_b}}"
    - name: create subnet c
      ec2_vpc_subnet:
        state: present
        region: "{{vpc_region}}"
        vpc_id: "{{vpc.vpc.id}}"
        cidr: "{{subnet_cidr_c}}"
        az: "{{az_c}}"  
   