
- name: EC2 creates VPC on ohio region 
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
    - name: create VPC with tags
      ec2_vpc_net:
        name: Miki_VPC
        cidr_block: 10.0.0.0/16
        region: us-east-2
        tags:
          name: miki_VPC
          tenancy: default       
    - name: Create subnet for database servers
      ec2_vpc_subnet:
      state: present
      vpc_id: vpc-123456
      cidr: 10.0.1.16/28
      resource_tags:
      name: Database Subnet
      register: database_subnet 
      
   