---
- name: Playbook for Provisioning
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  


#Private Subnet ------------------------------------
    - name: Create subnet for database servers
      ec2_vpc_subnet:
        state: present
        region: eu-central-1
        az: eu-central-1a
        vpc_id:  "{{vpc_info.vpcs[0].vpc_id}}"
        cidr: 10.10.1.0/24
        resource_tags:
          Name: Private Subnet
      register: private_subnet1


    - name: Create subnet for database servers
      ec2_vpc_subnet:
        state: present
        region: eu-central-1
        az: eu-central-1a
        vpc_id:  "{{vpc_info.vpcs[0].vpc_id}}"
        cidr: 10.10.2.0/24
        resource_tags:
          Name: Private Subnet
      register: private_subnet2 


    - name: Create subnet for database servers
      ec2_vpc_subnet:
        state: present
        region: eu-central-1
        az: eu-central-1a
        vpc_id:  "{{vpc_info.vpcs[0].vpc_id}}"
        cidr: 10.10.1.0/24
        resource_tags:
          Name: Private Subnet
      register: private_subnet3 
      
#Public Subnet ----------------------------------------
    - name: Create subnet for  web servers
      ec2_vpc_subnet:
        state: present
        region: eu-central-1
        az: eu-central-1b
        vpc_id:  "{{vpc_info.vpcs[0].vpc_id}}"
        cidr: 10.10.101.0/24
        resource_tags:
          Name: Public Subnet
      register: public_subnet1 


    - name: Create subnet for web servers
      ec2_vpc_subnet:
        state: present
        region: eu-central-1
        az: eu-central-1b
        vpc_id:  "{{vpc_info.vpcs[0].vpc_id}}"
        cidr: 10.10.102.0/24
        resource_tags:
          Name: Public Subnet
      register: public_subnet2  
    
    - name: Create subnet for web servers
      ec2_vpc_subnet:
        state: present
        region: eu-central-1
        az: eu-central-1b
        vpc_id:  "{{vpc_info.vpcs[0].vpc_id}}"
        cidr: 10.10.103.0/24
        resource_tags:
          Name: Public Subnet
      register: public_subnet3  
      