
- name: EC2 creates VPC on ohio region 
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
    - name: create VPC with tags
      ec2_vpc_net:
        name: Miki_VPC
        cidr_block: 10.0.0.0/16
        region: us-east-2
        tags:
          name: miki_VPC
          tenancy: default
    
    - name: create_subnet_a
      ec2_vpc_subnet:
        state: present
        region: "{{vpc_region}}"
        vpc_id: "{{vpc.vpc.id}}"
        cidr: "{{subnet_cidr_a}}"
        az: "{{az_a}}"

    - name: create_subnet_b
      ec2_vpc_subnet:
        state: present
        region: "{{vpc_region}}"
        vpc_id: "{{vpc.vpc.id}}"
        cidr: "{{subnet_cidr_b}}"
        az: "{{az_b}}"

    - name: create_subnet_c
      ec2_vpc_subnet:
        state: present
        region: "{{vpc_region}}"
        vpc_id: "{{vpc.vpc.id}}"
        cidr: "{{subnet_cidr_c}}"
        az: "{{az_c}}"

        
    - name: create security group
      ec2_group:
        name: "{{security_group_name}}"
        description: "{{description}}"
        vpc_id: "{{vpc.vpc.id}}"
        region: "{{vpc_region}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0